### ISSUE TITLE
parameter --devn not working

### ISSUE THREAD

**Issue by WarriorWithin** [svanas/nefertiti#1]
Telegram user: DanieleWW. I tested the --devn=0.97 parameter applyed to cryptoqualitysignal, when the IOST buy signal was sent at 0.00000083, it bought it anyway at 0.00000082 instead 0.00000080. This is the second time I check devn and it should apply the mult 0.97 deviation to any signal as I get it but apparently is not working. We will make more investigations our side, this parameter is very important because most times signals are issued they are subject to drop due to big whales high speculation over those ones, so they will use such as "pump signals" instead, turning in facts the signal to a quick panic sell before regaining value. So better take advantage of it either.

**Comment by svanas** [comment]
Fixed in 0.0.142
