### ISSUE TITLE
crypto.com API error persists

### ISSUE THREAD

**Issue by meatymouldia** [svanas/nefertiti#12]
please dont close issues that are not resolved, also try to think that not everyone is able to join chat groups and such and everyone is not neurologically the same, ie for autistic people chat groups are overwhelming and its not appropriate for us or the best place for to resolve errors. in fact this issue page is where github is supposed to resolve errors so im posting it here again. i have a bunch of scripts for your bot ill post them in my own github maybe you want to distribute them with the program. ill check your crypto.com code and see if i can find anything wrong. cheers

**Comment by svanas** [comment]
I must close issues that are vague and do not include reproducible steps, sorry. If there is an issue with crypto.com and you happen to have consistent, reproducible steps, then please reopen. Thanks!
