### ISSUE TITLE
crypto.com API does not send any sell orders 

### ISSUE THREAD

**Issue by meatymouldia** [svanas/nefertiti#13]
as far as i can tell according to how github works its not closed until the error is fixed and the error persists, im sorry i was too vague - i will attempt to be a lot more thorough now. i tried quite a few steps before posting, its never once sent a sell order to the exchange. hmmmm. it may be an API error on the exchange end, it may be the way im calling it.

would you like me to list all the exact steps from every method i tried (a lot) or just one of the ones that doesnt work? ive used the signals one, the default one, the dca one etc. what logs would help from the server ? they all dont work for me. one thing that may have affected it is sometimes im running it like this:

screen -dm -S "$layervar $MARKET" ./buy.sh $DIP $UNITS $MARKET

does the crypto.com sell API work at all for you ? its just never once sent a signal that was registered on the crypto.coms books for me. i cant think what it would be if it works for you, i was just thinking ah maybe he just doesnt use that one and didnt notice its not working.

i was trying to run layers of them because the sell bot only sells at one percentage (from what i can make out) so i buy more if it dips more to mitigate that. if it was possible to run multiple sell bots somehow on the same market that would be good. like 20% drop 7$ profit 15% drop 6% profit etc

my sell script is just this

cryptotrader sell --exchange=$EXCHANGE --api-key=$APIKEY --api-secret=$API_SECRET --pushover-app-key=$PUSHOVER_APP_KEY --pushover-user-key=$PUSHOVER_USER_KEY --telegram-app-key=0 --telegram-chat-id=0

my buy script is this with some variables sent to multiple copies of it in screen sessions as above

cryptotrader buy --valid=$VALID --top=$TOP --repeat=$REPEAT --exchange=$EXCHANGE --dip=$DIP --market=$MARKET --quote=$QUOTE --price=$UNITS --api-key=$APIKEY --api-secret=$API_SECRET --pushover-app-key=$PUSHOVER_APP_KEY --pushover-user-key=$PUSHOVER_USER_KEY --telegram-app-key=0 --telegram-chat-id=0

ill look into it more later, let me know if there is anything in particular i should be looking at to diagnose. i do have another server to test this on so ill try that again with a default buy/sell as well and post back.

thanks

**Comment by svanas** [comment]
> as far as i can tell according to how github works its not closed until the error is fixed

How this works is: as the admin of this project, I will close issues as I see fit.

>  it may be an API error on the exchange end, it may be the way im calling it

That is why I am asking you to take this matter to our Telegram group, where we can assist you. Github issues is not where we are providing support.

> does the crypto.com sell API work at all for you?

Yes. Here are two examples that have proven to work:
```
./nefertiti sell --exchange=crypto.com
```
and
```
./nefertiti buy --exchange=crypto.com --market=ADA_BTC,ICX_BTC,XRP_BTC,BCH_BTC,CRO_BTC,XTZ_BTC,ETH_BTC,VET_BTC,LTC_BTC,XLM_BTC,EOS_BTC,ATOM_BTC,LINK_BTC,ALGO_BTC,NEO_BTC,OMG_BTC,MANA_BTC,YFI_BTC,ONT_BTC,DOT_BTC,DOGE_BTC,UMA_BTC,ENJ_BTC --price=0.0025 --dca --top=1 --repeat=1
```
> let me know if there is anything in particular i should be looking at to diagnose

I suggest you rule out the `buy.sh` script you are using. The fewer moving parts, the easier it is to close in on a bug (if any).

**Comment by meatymouldia** [comment]
abelist.
