### ISSUE TITLE
1001 error, maybe false flag

### ISSUE THREAD

**Issue by WarriorWithin** [svanas/nefertiti#2]
Error 1001 is really more of a bother then else probably, but it's popping out everytime like a mad mole. I am not sure whether or not that issue leads to a real limitation, because I try to check everytime my orderbook and notice for any missed sell opportunity where applies. Atm this 1001 error didnt lead me to any loss apparently. This is just annoying because somehow it's like you keep have heads up without any apparent reason. More investigations on their way. 

![Immagine](https://user-images.githubusercontent.com/82939/108318014-6dd06c00-71bf-11eb-99a7-862793a2df86.jpg)

**Comment by svanas** [comment]
I have added a mitigation for the Binance -1001 error here: https://github.com/svanas/go-binance/commit/98ca547c4a8d9389247a98b25dcd577211e3791a

**Comment by WarriorWithin** [comment]
ok good

thank you

Il giorno ven 12 mar 2021 alle ore 20:29 Stefan ***@***.***>
ha scritto:
