### ISSUE TITLE
Feature suggestion: Volume filter for built-in strategies

### ISSUE THREAD

**Issue by rleons** [svanas/nefertiti#24]
**This is NOT an "issue", just a feature suggestion:**

**Description**: Make the `--volume=X` flag also available when using built-in strategies, currently, it's a signals-only option.

**Use case**: If this option is available globally, a good example use case would be to combine `--volume=X` with `--market=all`, resulting in the trade of all available markets for a specified `--quote` above `X` 24h trading volume.

**Comment by rleons** [comment]
NOTE: This would only work in exchanges that return a key with the 24h trading volume through one of the markets API call.

**Comment by svanas** [comment]
Fixed in 0.0.174
