### ISSUE TITLE
Order sizes don't respect the --price set in the buy script

### ISSUE THREAD

**Issue by hotzenwalder** [svanas/nefertiti#34]
When trading on WOO over time the order sizes drop to a size much lower than the set --price. 

In my example I trade with this buy command 

nefertiti buy --exchange=WOO --market=SPOT_WOO_USDT --api-key=* --api-secret=* --price=1000 --repeat=0.5 --top=2 --dca --ignore-error

The sell command

nefertiti sell --exchange=WOO --market=SPOT_WOO_USDT --api-key=* --api-secret=* --pushover-app-key=none --pushover-user-key=none --mult=1.05 --ignore-error

The first orders are fine and use a price of 1000 USDT or more but during the day I see orders coming in for only 15 USDT or less

Logfiles 
are attached so you can see the fluctuation in orders. Maybe this is just the DCA option doing it's work but I feels strange

[woo-sell-error.log](https://github.com/svanas/nefertiti/files/7347335/woo-sell-error.log)
[woo-buy-error.log](https://github.com/svanas/nefertiti/files/7347352/woo-buy-error.log)

I noticed that the bot was using a repeat of 0.5 so I switched back to the default of 1 to see if this gives an improvement

If you need more information feel free to contact me. Might not be an issue but just the way the bot works.

PENDING ORDERS
![Screenshot 2021-10-14 171815](https://user-images.githubusercontent.com/78266646/137347410-8a820e8d-d595-45c0-9ddf-6d25cdbf0819.png)

CANCELLED ORDERS
![Screenshot 2021-10-14 171750](https://user-images.githubusercontent.com/78266646/137347411-b8ca0e97-a007-4df2-9c23-121d721b6e95.png)

**Comment by hotzenwalder** [comment]
![image](https://user-images.githubusercontent.com/78266646/137961038-d2dc352c-99d3-4851-8bec-b98519ca0db2.png)

here's an example of the order size not respecting the price of --price=1000 --top=2

**Comment by svanas** [comment]
Fixed in https://github.com/svanas/nefertiti/commit/84a83f1a8f170e7d177849b876b7a3e7641dcff1
