### ISSUE TITLE
Order book too thin error on ETH/USDT pair when there is enough volume (WOO exchange)

### ISSUE THREAD

**Issue by hotzenwalder** [svanas/nefertiti#44]
I keep getting the below error when trying to trade the SPOT_ETH_USDT pair on WOO exchange with the below settings

nefertiti buy --exchange=WOO --market=SPOT_ETH_USDT,SPOT_BNB_USDT --api-key=* --api-secret=* --pushover-app-key=* --pushover-user-key=* --price=125 --repeat=1 --strict --top=2 --ignore=error

The error is

2021/10/29 10:37:14 [ERROR] buy.go:command.buy:223 Cannot find any supports. Order book is too thin. Please reconsider this market. Market: SPOT_ETH_USDT.

It seems strange when looking at the daily volume for this pair. There is a lot more volume for the ETH/USDT pair than we see on the EWOO/USDT pair yet the WOO/USDT pair can be traded without any problem with the same settings (but against a higher --price)

![image](https://user-images.githubusercontent.com/78266646/139404605-0ebb6f40-cfc6-4849-8c59-c0b5b543f25f.png)

**Comment by svanas** [comment]
Have you tried to remove `--strict`? You should see fewer "cannot find any supports" without `--strict`. While ETH-USDT might have more volume than WOO-USDT, there are other factors at play, for example: how many (unsold) sell orders you have open in your book.
