### ISSUE TITLE
idea pool about figuring out how to not be left holding bags / buying tops

### ISSUE THREAD

**Issue by katmai** [svanas/nefertiti#47]
i have been wondering if it would make sense for the bot not to rebuy the same coin via DCA if it was previously sold, to prevent it from buying a top and just be left with holding bags.

how about if a coin was sold recently, and on the next run (in 1 hour or what the timer is set to run) it wants to rebuy it due to DCA, maybe just buy it only once and then it puts it on a 24 hours cooldown in order not to DCA on the way up?

The behavior that made me think about this possible enhancement is this:
- coin - MKR
- I had about 10 DCA-filled orders x 50$ per order, so that brought the total amount of my DCA buys to ~500$. 
- The other day MKR pumped, and the 5% profit-taking sales happened. all good.
- later during the evening, we started DCA-ing back in, and I'm now sitting at a higher price buy-in than before due to DCA, while the price kept tanking.

So what i am thinking is to apply the same logic that we sometimes apply in trading: if profit was made, maybe take 1 position, but then DCA takes a little break of 1 day for that specific coin, to let things cool down, just chill out and enjoy the profits.

There are plays every day

i appreciate any other feedback or criticism brought forward to the logic outlined here. there may be flaws that i can't see.

**Comment by TaipeiHere** [comment]
perhaps one way is to 'pause trading' on the market for time=X if there is a price increase=Y%?  what do you think, and how could that be more intelligently expressed?

**Comment by katmai** [comment]
actually thinking about this, i think it's wiser to wait a little longer to get more experience with the behavior (only have about 3 weeks of usage so far) and things are looking quite well, so this might not actually be an issue.
