### ISSUE TITLE
minor annoyance: 'notify' command always asks for pushover

### ISSUE THREAD

**Issue by d00vy** [svanas/nefertiti#49]
Trying to send a test message to Telegram with:
`$: nefertiti.exe notify --telegram-app-key=XXXXX --telegram-chat-id=XXXXX --msg="This is a test message"`
But the operation always pauses to ask for Pushover application key. 

Can we add a way to distinguish between notification services, or maybe bypass the user input if the command is given with keys?

**Comment by TaipeiHere** [comment]
does adding this to the command line help?

**Comment by d00vy** [comment]
> does adding this to the command line help? 
> --pushover-app-key=none

Yes, but that's the "minor annoyance" 🙃
