### ISSUE TITLE
NEF Sellbot crashes regulary on GDAX

### ISSUE THREAD

**Issue by p0ll3** [svanas/nefertiti#54]
The sellbot crashes/stops running once in a while. For example, all my sellbots started the same time 9 days ago, only the gdax sellbot stopped and got restarted after 5 days with this message. You probably need the Debug log? I will deliver when it crashes next time. It does that multiple times a month.

71995 : 2021/11/29 15:39:32 [INFO] {"price":"0.0000775","order_id":"626d38d0-0e49-4a01-985c-beaddad5cf79","remaining_size":"4.52","type":"open","side":"buy","product_id":"XTZ-BTC","time":"2021-11-29T14:39:32.275027Z","sequence":2866174297,"profile_id":"e3228956-a7c9-414a-a99f-26ea26026191","user_id":"59f47d5cdc9ca90107508b97"}
71996 : 2021/11/29 15:54:23 [ERROR] gdax.go:exchanges.(*Gdax).sell:318 read tcp [2003:dc:df03:5100:5054:ff:fe27:ed69]:51938->[2606:4700::6812:fed]:443: read: connection timed out
71997 : 2021/11/29 15:54:24 [ERROR] sell.go:command.(*SellCommand).Run:85 read tcp [2003:dc:df03:5100:5054:ff:fe27:ed69]:51938->[2606:4700::6812:fed]:443: read: connection timed out
71998 : 2021/11/29 15:54:27 [INFO] Listening to wss://ws-feed.pro.coinbase.com (user: 59f47d5cdc9ca90107508b97)
71999 : 2021/11/29 15:54:27 [INFO] Listening to Coinbase Pro...

Sellbot: 

#!/bin/bash
set -u
echo $(date +"%Y/%m/%d %H:%M:%S") - GDAX Sell Bot Started
nef sell --exchange=GDAX --api-key= --api-secret= --api-passphrase= --pushover-app-key=NONE --pushover-user-key=NONE --telegram-app-key= --telegram-chat-id= --ignore-error --mult=1.03 --notify=1 --earn=BTC-EUR,ETH-EUR,BCH-EUR,ADA-EUR,BTC-USDC,ETH-USDC,ADA-BTC,ETH-BTC,BCH-BTC

**Comment by svanas** [comment]
What makes you believe the sell bot crashed? As far as I can tell from looking at your log, the sell bot did encounter a few TCP/IP errors, but it then recuperated and reconnected. Am I missing something?

**Comment by p0ll3** [comment]
My bad and confusing. Line 71998 only happened because pm2 restarted the bot. The bot crashed after the tcp timeout. Line 71997

**Comment by svanas** [comment]
pm2 did not restart the bot. The bot restarted itself on line 71998.

**Comment by p0ll3** [comment]
> pm2 did not restart the bot. The bot restarted itself on line 71998

It definitly restarted, at least it had rerun the shellscript which echos this
thats the STDOUT log
7898 : 2021/11/26 02:25:16 - GDAX Sell Bot Started
7899 : Starting script sell bot script...
7900 : 2021/11/29 15:54:24 - GDAX Sell Bot Started

Could it be that without --debug the console doesn't put out the error message?

more Info:
The Sellbot crashed again, but this time I had --debug enabled:

73158 : 2021/12/08 20:26:42 [ERROR] websocket: close 1006 (abnormal closure): unexpected EOF
73159 : 2021/12/08 20:26:52 [ERROR] gdax.go:exchanges.(*Gdax).sell:297 websocket: bad handshake
73160 : 2021/12/08 20:26:52 [ERROR] sell.go:command.(*SellCommand).Run:85 websocket: bad handshake
73161 : C:/Projects/nefertiti/exchanges/gdax.go:295 (0x889bcd)
73162 : C:/Projects/nefertiti/exchanges/gdax.go:591 (0x88b8bb)
73163 : C:/Projects/nefertiti/command/sell.go:84 (0x93a312)
73164 : C:/Users/Stefan van As/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 (0x7ab45a)
73165 : C:/Projects/nefertiti/main.go:143 (0x93de07)
73166 : C:/Program Files/Go/src/runtime/proc.go:225 (0x438b16)
73167 : C:/Program Files/Go/src/runtime/asm_amd64.s:1371 (0x46bd81)
73168 : 2021/12/08 20:26:52 [DEBUG] GET https://api.pro.coinbase.com/products
73169 : 2021/12/08 20:26:53 [DEBUG] sleeping 0.098773 seconds
73170 : 2021/12/08 20:26:53 [DEBUG] GET https://api.pro.coinbase.com/users/self
73171 : 2021/12/08 20:26:57 [DEBUG] GET https://api.pro.coinbase.com/products
73172 : 2021/12/08 20:26:57 [INFO] Listening to wss://ws-feed.pro.coinbase.com (user: 59f47d5cdc9ca90107508b97)
73173 : 2021/12/08 20:26:57 [INFO] Listening to Coinbase Pro...


the STDOUT says it restarted @ 2021/12/08 20:26:52, so 73168 is probably the first Line of the restart.
7905 : 2021/12/05 19:46:00 - GDAX Sell Bot Started - with Debug1
7906 : 2021/12/08 20:26:52 - GDAX Sell Bot Started - with Debug1

**Comment by svanas** [comment]
> Could it be that without --debug the console doesn't put out the error message?

Without --debug you do not get a stack trace with the error, otherwise you do.
