### ISSUE TITLE
BINANCE: Error 429

### ISSUE THREAD

**Issue by stfrbrntyu** [svanas/nefertiti#55]
I get below messages from time to time, specially during drops.
It's an error 429 and it returns the time to wait until contacting the API again to prevent being IP banned from Binance.

Would it be possible to interact with error 429 and let the bot wait the amount of seconds returned by error 429?

2021/12/04 06:39:31 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:31 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:31 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:31 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:31 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:31 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:31 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:31 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:31 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:31 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:32 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:32 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:32 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:32 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:32 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:32 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:32 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:32 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:32 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:32 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:32 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:32 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:32 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:32 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:32 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 35
2021/12/04 06:39:32 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 34
2021/12/04 06:39:32 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 34
2021/12/04 06:39:32 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 34
2021/12/04 06:39:32 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 34
2021/12/04 06:39:32 [ERROR] binance.go:exchanges.(*Binance).listen:384 Too Many Requests: retry after 34

from: https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#ip-limits

IP Limits
- Every request will contain X-MBX-USED-WEIGHT-(intervalNum)(intervalLetter) in the response headers which has the current used weight for the IP for all request rate limiters defined.
- Each route has a weight which determines for the number of requests each endpoint counts for. Heavier endpoints and endpoints that do operations on multiple symbols will have a heavier weight.
- **When a 429 is received, it's your obligation as an API to back off and not spam the API.**
- Repeatedly violating rate limits and/or failing to back off after receiving 429s will result in an automated IP ban (HTTP status 418).
- IP bans are tracked and scale in duration for repeat offenders, from 2 minutes to 3 days.
- A Retry-After header is sent with a 418 or 429 responses and will give the number of seconds required to wait, in the case of a 429, to prevent a ban, or, in the case of a 418, until the ban is over.
- The limits on the API are based on the IPs, not the API keys.

Order Rate Limits
- Every successful order response will contain a X-MBX-ORDER-COUNT-(intervalNum)(intervalLetter) header which has the current order count for the account for all order rate limiters defined. To monitor order count usage, refer to GET api/v3/rateLimit/order.
- When the order count exceeds the limit, you will receive a 429 error without the Retry-After header. Please check the Order Rate Limit rules using GET api/v3/exchangeInfo and wait for reactivation accordingly.
- Rejected/unsuccessful orders are not guaranteed to have X-MBX-ORDER-COUNT-** headers in the response.
- The order rate limit is counted against each account.

**Comment by svanas** [comment]
Are you or any other piece of software communicating with a Binance endpoint from the same IP address? [We go though great length trying to respect the Binance rate limit(s)](https://github.com/svanas/nefertiti/blob/master/exchanges/binance.go#L60-L73). 429s shouldn't happen.

**Comment by stfrbrntyu** [comment]
I only have one computer running NEF (1 sell, 4 buy)

The line before the error is always a OPEN           "side":"SELL"
It mostly happens when a drop happens.

I can send a log file via telegram if you want

**Comment by stfrbrntyu** [comment]
2021/12/17 07:12:59 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
2021/12/17 12:12:59 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
2021/12/17 13:12:59 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
2021/12/17 14:12:59 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
2021/12/17 17:13:00 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.

**Comment by stfrbrntyu** [comment]
Line 7365: 2021/12/17 07:12:59 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 7446: 2021/12/17 12:12:59 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 7467: 2021/12/17 13:12:59 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 7481: 2021/12/17 14:12:59 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 7578: 2021/12/17 17:13:00 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 8382: 2021/12/21 07:22:55 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 8383: 2021/12/21 07:22:57 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 8384: 2021/12/21 07:22:59 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 8391: 2021/12/21 09:22:59 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 8398: 2021/12/21 10:22:55 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 8399: 2021/12/21 10:22:57 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 8405: 2021/12/21 11:22:57 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 8424: 2021/12/21 13:22:58 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 8430: 2021/12/21 14:22:57 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 8438: 2021/12/21 15:22:54 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 8439: 2021/12/21 15:22:57 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 8440: 2021/12/21 16:22:59 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 8447: 2021/12/21 17:22:55 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 8448: 2021/12/21 17:22:58 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 8456: 2021/12/21 18:22:57 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 8465: 2021/12/21 19:22:54 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 8466: 2021/12/21 19:22:56 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 8467: 2021/12/21 19:22:59 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 8477: 2021/12/21 20:22:56 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
	Line 8478: 2021/12/21 20:22:59 [ERROR] binance.go:exchanges.(*Binance).Sell:682 <APIError> code=-1003, msg=Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
