### ISSUE TITLE
Multiple pair for—quote fails

### ISSUE THREAD

**Issue by chroots** [svanas/nefertiti#58]
I ran into problems with Nefertiti bot did not do anything to place new deal orders when you have —quote=USDT,USD,USDC basically stayed sleep forever no action till I tried put single pair E.g. —quote=ISDT suddenly bot started active crazy buy buy buy 100+ coins in USDT or single USD even —signals=cryptobasescanner.com with —quote=USD or USDT it worked placement new deal orders when received signaling. 

The solution I can able run 3 buy bots with each —quote in USD, USDT, USDC with single sell bot. Worked as champ as smooth silky.

**Comment by TaipeiHere** [comment]
Yes, one each BUY bot can handle one --quote=

thank you for documenting this and sharing!

**Comment by svanas** [comment]
@TaipeiHere reminded me that if we allow for comma-separated quote assets here, then...
1. we also need to allow for comma-separated --price, or
2. we need to disallow for --price and only allow for --size

@chroots is this a price you are willing to pay for this "feature"? If not, then please close this issue. Thanks!

**Comment by chroots** [comment]
Alright, No worries, I am running separated bot each currency and I go ahead close this issue
