### ISSUE TITLE
bot responds to old orders with a market sell

### ISSUE THREAD

**Issue by d00vy** [svanas/nefertiti#59]
KuCoin API spits out ancient order fills, and Nefertiti responds by market selling as if it's a new purchase.

Nefertiti really needs a way to check orders for validity by _at least_ checking the date-time stamps to be sure the order is relevant and not from 2 years ago.

**Comment by svanas** [comment]
I looked into the KuCoin API. Unfortunately, the [recent fills](https://docs.kucoin.com/?lang=en_US#list-fills) do not tell us when the order got filled (it does tell us when the order got created, but that could be weeks -- if not months -- ago). Consequently we cannot do [what we do for Binance](https://github.com/svanas/nefertiti/blob/master/exchanges/binance.go#L424-L429), where we filter the orders that got filled during the last 24 hours and ignore everything else. I wish there was around this nonsense, but the KuCoin API sucks.

**Comment by d00vy** [comment]
Nef buy bot cancels all open orders on the API, and issues new ones on every `--repeat`. 

How about filtering for filled orders within that time frame?
