### ISSUE TITLE
Nef sell bot died every time Network down.

### ISSUE THREAD

**Issue by chroots** [svanas/nefertiti#63]
I noticed Nef sell bot easily stopped and died after the Network goes down for some reason except Nef buy bots no problem did not gave up and it kept trying without dying.

--- Nef sell bot config ---

./nefertiti_darwin_arm64 sell \
	--exchange=GDAX \
	--quote=USDT \
	--market=all \
	--api-key=*** \
	--api-secret=*** \
	--api-passphrase=*** \
	--telegram-app-key=*** \
	--telegram-chat-id=*** \
	--ignore=error \
	--pushover-app-key=* \
	--pushover-user-key=* \
	--ignore-error \
	--debug

--- Nef sell config End---

--- Log Nef sell --
chrootz-Mac-mini % ./nefsell.sh
2021/12/11 19:03:38 [DEBUG] GET https://api.pro.coinbase.com/products
2021/12/11 19:03:38 [DEBUG] sleeping 0.098275 seconds
2021/12/11 19:03:38 [DEBUG] GET https://api.pro.coinbase.com/users/self
2021/12/11 19:03:40 [DEBUG] GET https://api.pro.coinbase.com/products
2021/12/11 19:03:40 [INFO] Listening to wss://ws-feed.pro.coinbase.com (user: ***)
2021/12/11 19:03:40 [INFO] Listening to Coinbase Pro...
2021/12/12 03:51:55 [ERROR] read tcp 192.168.3.101:52061->104.18.15.237:443: read: connection reset by peer
2021/12/12 03:52:00 [DEBUG] GET https://api.pro.coinbase.com/products
2021/12/12 03:52:01 [INFO] Listening to wss://ws-feed.pro.coinbase.com (user: ***)
2021/12/12 05:58:36 [ERROR] read tcp 192.168.3.101:52865->104.18.15.237:443: read: connection reset by peer
2021/12/12 05:58:42 [DEBUG] GET https://api.pro.coinbase.com/products
2021/12/12 05:58:42 [INFO] Listening to wss://ws-feed.pro.coinbase.com (user: ***)
2021/12/12 09:17:14 [ERROR] read tcp 192.168.3.101:52969->104.18.15.237:443: read: connection reset by peer
2021/12/12 09:17:19 [DEBUG] GET https://api.pro.coinbase.com/products
2021/12/12 09:17:19 [INFO] Listening to wss://ws-feed.pro.coinbase.com (user: ***)
2021/12/12 09:33:56 [ERROR] read tcp 192.168.3.101:53033->104.18.15.237:443: read: connection reset by peer
2021/12/12 09:34:01 [DEBUG] GET https://api.pro.coinbase.com/products
2021/12/12 09:34:01 [INFO] Listening to wss://ws-feed.pro.coinbase.com (user: ***)
2021/12/12 09:50:16 [ERROR] read tcp 192.168.3.101:53043->104.18.14.237:443: read: connection reset by peer
2021/12/12 09:50:21 [DEBUG] GET https://api.pro.coinbase.com/products
2021/12/12 11:23:39 [ERROR] gdax.go:exchanges.(*Gdax).sell:311 Get "https://api.pro.coinbase.com/products": dial tcp: lookup api.pro.coinbase.com on 8.8.4.4:53: write udp 192.168.3.101:59941->8.8.4.4:53: write: network is down
2021/12/12 11:23:39 [ERROR] sell.go:command.(*SellCommand).Run:85 Get "https://api.pro.coinbase.com/products": dial tcp: lookup api.pro.coinbase.com on 8.8.4.4:53: write udp 192.168.3.101:59941->8.8.4.4:53: write: network is down
chrootz-Mac-mini % 

--- End Log ---

**Comment by svanas** [comment]
You need to check this box labelled "Prevent computer from sleeping automatically when the display is off"
![Screen Shot 2021-12-21 at 06 31 53](https://user-images.githubusercontent.com/787861/146876856-98417c93-2ead-4043-8cd6-6aafd8d7cc68.png)
