### ISSUE TITLE
Potential JSON error

### ISSUE THREAD

**Issue by TaipeiHere** [svanas/nefertiti#70]
—market=all

randomly crashes

021/12/24 06:00:36 [{"market":"mkreth","price":0.5692,"size":0.001933}]
2021/12/24 06:00:36 [DEBUG] sleeping 0.098953 seconds
2021/12/24 06:00:36 [DEBUG] GET /market/trade
2021/12/24 06:00:36 [DEBUG] sleeping 0.099515 seconds
2021/12/24 06:00:36 [DEBUG] GET /market/detail
2021/12/24 06:00:36 [DEBUG] sleeping 0.098387 seconds
2021/12/24 06:00:36 [DEBUG] GET /market/trade
2021/12/24 06:00:37 [DEBUG] sleeping 0.098806 seconds
2021/12/24 06:00:37 [DEBUG] GET /market/depth
2021/12/24 06:00:38 [DEBUG] sleeping 0.099569 seconds
2021/12/24 06:00:38 [DEBUG] GET /market/depth
2021/12/24 06:00:38 [ERROR] buy.go:command.(*BuyCommand).Run:847 json: unsupported value: +Inf

**Comment by svanas** [comment]
What does this request tell you? https://api.huobi.pro/market/depth?type=step0&symbol=mkreth

**Comment by svanas** [comment]
Fixed in https://github.com/svanas/nefertiti/commit/7e57a9ed3124d23c50e7e246d7ab9542dc9f718d
