### ISSUE TITLE
CBS signal override mediandrop needed

### ISSUE THREAD

**Issue by chroots** [svanas/nefertiti#72]
I am getting fumbled ton times with CryptoBaseScanner Signal and request add the override median drop where it would trigger place new deal order.

E.g. example --debug:

[DEBUG] Ignoring orn-usdt because latestBase.currentDrop: -3.355705 is above marketStats[day_trade].medianDrop: -7.650000

override median drop rate E.g.

./Nefertiti buy --signal=CBS --signal-key=** --mediandrop=1.04 or 1.05 (4% or 5%) since I am on GDAX low volume.

[DEBUG] Ignoring orn-usdt because latestBase.currentDrop: -3.355705 is above marketStats[day_trade].medianDrop: -4.00 (override by --mediandrop)

**Comment by svanas** [comment]
I decided to piggyback on `--dip` for this "feature". You can pass `--dip=[any value other than zero]` and it should override `marketStats[day_trade].medianDrop`, for example `--dip=5 `
