### ISSUE TITLE
On GDAX with --market=all --> --volume= is ignored

### ISSUE THREAD

**Issue by p0ll3** [svanas/nefertiti#75]
The command:

`nef buy --ignore-error --exchange=GDAX --market=all --quote=BTC --price=0.00035 --top=1 --repeat=1.0 --strict --notify=2 --mult=1.03 --test --volume=500`

should result in ~5 markets on GDAX, but the results look like that its just all of them. If I remember correctly the GDAX api doesn't provide the Volume in BTC, only in coinvalue. Perhaps its not converted to BTC.

`
C:\Users\noroot>nef buy --api-key= --api-secret= --telegram-app-key= --telegram-chat-id= --pushover-app-key=NONE --pushover-user-key=NONE --ignore-error --exchange=GDAX --market=all --quote=BTC --price=0.00035 --api-passphrase= --top=1 --repeat=1.0 --strict --notify=2 --mult=1.03 --test --volume=500
2022/01/09 20:22:49 [{"market":"ETC-BTC","price":0.0005,"size":664.8425942}]
2022/01/09 20:22:50 [{"market":"TRB-BTC","price":0.00065,"size":77.87800000000001}]
2022/01/09 20:22:51 [{"market":"WBTC-BTC","price":0.95,"size":0.37908359999999997}]
2022/01/09 20:22:53 [{"market":"MKR-BTC","price":0.04,"size":3.689146}]
2022/01/09 20:22:54 [{"market":"TRU-BTC","price":0.0000055,"size":27561.899999999998}]
2022/01/09 20:22:55 [{"market":"AXS-BTC","price":0.0016,"size":395.3999999999999}]
2022/01/09 20:22:56 [{"market":"AAVE-BTC","price":0.00375,"size":52.26000000000001}]
2022/01/09 20:22:58 [{"market":"ENJ-BTC","price":0.000045,"size":6790.38}]
2022/01/09 20:22:59 [{"market":"WCFG-BTC","price":0.000018,"size":19118.870000000003}]
2022/01/09 20:23:01 [{"market":"REP-BTC","price":0.000325,"size":471.43120100000004}]
2022/01/09 20:23:02 [{"market":"WLUNA-BTC","price":0.00135,"size":596.1750000000001}]
2022/01/09 20:23:03 [{"market":"MIR-BTC","price":0.00004,"size":3648.0400000000004}]
2022/01/09 20:23:04 [{"market":"BTRST-BTC","price":0.00007,"size":24071.83}]
2022/01/09 20:23:05 [{"market":"NKN-BTC","price":0.0000067,"size":12706}]
2022/01/09 20:23:07 [{"market":"SKL-BTC","price":0.00000375,"size":35412.200000000004}]
2022/01/09 20:23:08 [{"market":"BAND-BTC","price":0.0001,"size":2139.8}]
2022/01/09 20:23:10 [{"market":"SOL-BTC","price":0.0027,"size":2424.632999999997}]
2022/01/09 20:23:11 [{"market":"LRC-BTC","price":0.000035,"size":37796}]
2022/01/09 20:23:13 [{"market":"UNI-BTC","price":0.00035,"size":3677.3999999999965}]
2022/01/09 20:23:14 [{"market":"OGN-BTC","price":0.0000115,"size":12363.62}]
2022/01/09 20:23:15 [{"market":"SUSHI-BTC","price":0.00015,"size":3296.880000000001}]
2022/01/09 20:23:16 [{"market":"LTC-BTC","price":0.0022,"size":1121.0860549200002}]
2022/01/09 20:23:17 [{"market":"STORJ-BTC","price":0.000035,"size":12915.989999999998}]
2022/01/09 20:23:19 [{"market":"MATIC-BTC","price":0.000045,"size":26104.30000000001}]
2022/01/09 20:23:25 [{"market":"CRV-BTC","price":0.000085,"size":25218.190000000002}]
2022/01/09 20:23:26 [{"market":"FIL-BTC","price":0.00065,"size":207.886}]
2022/01/09 20:23:27 [{"market":"ORN-BTC","price":0.0001,"size":753.0799999999999}]
2022/01/09 20:23:28 [{"market":"NMR-BTC","price":0.000525,"size":105.54100000000001}]
2022/01/09 20:23:29 [{"market":"ZRX-BTC","price":0.000013,"size":20189.49073}]
2022/01/09 20:23:31 [{"market":"LINK-BTC","price":0.000475,"size":4735.18}]
2022/01/09 20:23:32 [{"market":"YFI-BTC","price":0.75,"size":1.4328599999999998}]
2022/01/09 20:23:33 [{"market":"CGLD-BTC","price":0.0001,"size":3633.180000000004}]
2022/01/09 20:23:35 [{"market":"UMA-BTC","price":0.00018,"size":3106.9469999999988}]
2022/01/09 20:23:36 [{"market":"COMP-BTC","price":0.004,"size":116.09800000000007}]
2022/01/09 20:23:37 [{"market":"OMG-BTC","price":0.00012,"size":1856.1000000000001}]
2022/01/09 20:23:38 [{"market":"ZEN-BTC","price":0.00125,"size":48.768}]
2022/01/09 20:23:40 [{"market":"XTZ-BTC","price":0.00008,"size":14175.030000000002}]
2022/01/09 20:23:41 [ERROR] buy.go:command.buy:224 Cannot find any supports. Order book is too thin. Please reconsider this market. Market: IOTX-BTC.
2022/01/09 20:23:43 [{"market":"GRT-BTC","price":0.000013,"size":65882.97}]
2022/01/09 20:23:45 [{"market":"ICP-BTC","price":0.0007,"size":653.4863999999997}]
2022/01/09 20:23:46 [{"market":"ZEC-BTC","price":0.0025,"size":266.885}]
2022/01/09 20:23:47 [{"market":"ALGO-BTC","price":0.000028,"size":669789}]
2022/01/09 20:23:48 [{"market":"BAL-BTC","price":0.000325,"size":443.2699999999996}]
2022/01/09 20:23:50 [{"market":"FORTH-BTC","price":0.00017,"size":382.06999999999994}]
2022/01/09 20:23:51 [{"market":"EOS-BTC","price":0.000063,"size":6047.900000000001}]
2022/01/09 20:23:52 [{"market":"ANKR-BTC","price":0.000002,"size":82061}]
2022/01/09 20:23:55 [{"market":"ETH-BTC","price":0.06,"size":803.4088254399992}]
2022/01/09 20:23:56 [{"market":"BAT-BTC","price":0.000021,"size":55369.670000000006}]
2022/01/09 20:23:58 [{"market":"KNC-BTC","price":0.000035,"size":27396.799999999992}]
2022/01/09 20:23:59 [{"market":"XYO-BTC","price":6.5e-7,"size":1597272.2999999998}]
2022/01/09 20:24:01 [{"market":"NU-BTC","price":0.000014,"size":30882}]
2022/01/09 20:24:02 [{"market":"CTSI-BTC","price":0.000013,"size":120859.30000000003}]
2022/01/09 20:24:03 [{"market":"DASH-BTC","price":0.0029,"size":424.343}]
2022/01/09 20:24:05 [{"market":"ATOM-BTC","price":0.0007,"size":3537.4999999999977}]
2022/01/09 20:24:06 [{"market":"ADA-BTC","price":0.00002,"size":240621.01}]
2022/01/09 20:24:08 [{"market":"SNX-BTC","price":0.000115,"size":1708.29}]
2022/01/09 20:24:10 [{"market":"1INCH-BTC","price":0.0000425,"size":5080.989999999999}]
2022/01/09 20:24:11 [{"market":"REN-BTC","price":0.00001,"size":158159}]
2022/01/09 20:24:13 [{"market":"AVAX-BTC","price":0.0016,"size":4277.348999999999}]
2022/01/09 20:24:14 [{"market":"XLM-BTC","price":0.0000055,"size":343262}]
2022/01/09 20:24:16 [{"market":"BNT-BTC","price":0.00007,"size":678}]
2022/01/09 20:24:17 [{"market":"BCH-BTC","price":0.0085,"size":143.19131233}]
2022/01/09 20:24:18 [{"market":"RAD-BTC","price":0.00019,"size":1818.91}]
2022/01/09 20:24:19 [{"market":"DOT-BTC","price":0.00055,"size":3345.7189999999996}]
2022/01/09 20:24:21 [{"market":"DOGE-BTC","price":0.0000034,"size":1763706.0999999999}]
2022/01/09 20:24:22 [{"market":"RLC-BTC","price":0.00006,"size":2064.94}]
2022/01/09 20:24:23 [{"market":"REQ-BTC","price":0.000006,"size":56767}]
2022/01/09 20:24:25 [{"market":"MANA-BTC","price":0.000065,"size":44898.07000000001}]
`

**Comment by svanas** [comment]
We do use the volume in BTC, if there is a BTC-paired market to be found https://github.com/svanas/nefertiti/blob/master/exchanges/gdax.go#L845-L860

**Comment by svanas** [comment]
@p0ll3 what version are you running? because here is the feedback I get from NEF 0.0.198 running your cmd line:
```
2022/01/11 14:00:16 [INFO] Ignoring TRU-BTC because volume 0.56 is lower than 500.00 BTC
2022/01/11 14:00:17 [INFO] Ignoring WCFG-BTC because volume 1.44 is lower than 500.00 BTC
2022/01/11 14:00:17 [INFO] Ignoring DASH-BTC because volume 5.82 is lower than 500.00 BTC
2022/01/11 14:00:18 [INFO] Ignoring EOS-BTC because volume 7.88 is lower than 500.00 BTC
2022/01/11 14:00:19 [INFO] Ignoring REQ-BTC because volume 3.03 is lower than 500.00 BTC
2022/01/11 14:00:20 [INFO] Ignoring ADA-BTC because volume 138.59 is lower than 500.00 BTC
2022/01/11 14:00:20 [INFO] Ignoring BAL-BTC because volume 3.47 is lower than 500.00 BTC
2022/01/11 14:00:21 [INFO] Ignoring NMR-BTC because volume 1.35 is lower than 500.00 BTC
2022/01/11 14:00:22 [INFO] Ignoring 1INCH-BTC because volume 2.02 is lower than 500.00 BTC
2022/01/11 14:00:22 [INFO] Ignoring ZRX-BTC because volume 2.06 is lower than 500.00 BTC
2022/01/11 14:00:23 [INFO] Ignoring COMP-BTC because volume 8.39 is lower than 500.00 BTC
2022/01/11 14:00:23 [INFO] Ignoring SOL-BTC because volume 187.51 is lower than 500.00 BTC
2022/01/11 14:00:24 [INFO] Ignoring ZEN-BTC because volume 4.90 is lower than 500.00 BTC
2022/01/11 14:00:25 [INFO] Ignoring NU-BTC because volume 3.99 is lower than 500.00 BTC
2022/01/11 14:00:26 [INFO] Ignoring XTZ-BTC because volume 22.71 is lower than 500.00 BTC
2022/01/11 14:00:26 [INFO] Ignoring NKN-BTC because volume 1.34 is lower than 500.00 BTC
2022/01/11 14:00:28 [INFO] Ignoring OMG-BTC because volume 21.06 is lower than 500.00 BTC
2022/01/11 14:00:28 [INFO] Ignoring ANKR-BTC because volume 5.23 is lower than 500.00 BTC
2022/01/11 14:00:29 [INFO] Ignoring GRT-BTC because volume 16.27 is lower than 500.00 BTC
2022/01/11 14:00:30 [INFO] Ignoring BAND-BTC because volume 2.98 is lower than 500.00 BTC
2022/01/11 14:00:30 [INFO] Ignoring WBTC-BTC because volume 92.19 is lower than 500.00 BTC
2022/01/11 14:00:31 [INFO] Ignoring ICP-BTC because volume 313.34 is lower than 500.00 BTC
2022/01/11 14:00:32 [INFO] Ignoring CTSI-BTC because volume 1.35 is lower than 500.00 BTC
2022/01/11 14:00:32 [INFO] Ignoring BAT-BTC because volume 5.68 is lower than 500.00 BTC
2022/01/11 14:00:33 [INFO] Ignoring CRV-BTC because volume 73.67 is lower than 500.00 BTC
2022/01/11 14:00:34 [INFO] Ignoring ATOM-BTC because volume 157.44 is lower than 500.00 BTC
2022/01/11 14:00:34 [INFO] Ignoring SNX-BTC because volume 14.30 is lower than 500.00 BTC
2022/01/11 14:00:35 [INFO] Ignoring ALGO-BTC because volume 28.40 is lower than 500.00 BTC
2022/01/11 14:00:36 [INFO] Ignoring KNC-BTC because volume 4.75 is lower than 500.00 BTC
2022/01/11 14:00:37 [INFO] Ignoring AXS-BTC because volume 11.18 is lower than 500.00 BTC
2022/01/11 14:00:37 [INFO] Ignoring TRB-BTC because volume 2.84 is lower than 500.00 BTC
2022/01/11 14:00:38 [INFO] Ignoring ETC-BTC because volume 26.90 is lower than 500.00 BTC
2022/01/11 14:00:39 [INFO] Ignoring UMA-BTC because volume 4.89 is lower than 500.00 BTC
2022/01/11 14:00:40 [INFO] Ignoring CGLD-BTC because volume 15.39 is lower than 500.00 BTC
2022/01/11 14:00:40 [INFO] Ignoring RLC-BTC because volume 0.99 is lower than 500.00 BTC
2022/01/11 14:00:41 [INFO] Ignoring AAVE-BTC because volume 22.50 is lower than 500.00 BTC
2022/01/11 14:00:42 [INFO] Ignoring SUSHI-BTC because volume 36.46 is lower than 500.00 BTC
2022/01/11 14:00:42 [INFO] Ignoring STORJ-BTC because volume 24.82 is lower than 500.00 BTC
2022/01/11 14:00:43 [INFO] Ignoring REN-BTC because volume 10.33 is lower than 500.00 BTC
2022/01/11 14:00:43 [INFO] Ignoring XLM-BTC because volume 29.44 is lower than 500.00 BTC
2022/01/11 14:00:44 [INFO] Ignoring FIL-BTC because volume 54.34 is lower than 500.00 BTC
2022/01/11 14:00:45 [INFO] Ignoring ZEC-BTC because volume 21.04 is lower than 500.00 BTC
2022/01/11 14:00:46 [INFO] Ignoring RAD-BTC because volume 6.22 is lower than 500.00 BTC
2022/01/11 14:00:46 [INFO] Ignoring XYO-BTC because volume 2.15 is lower than 500.00 BTC
2022/01/11 14:00:47 [INFO] Ignoring YFI-BTC because volume 40.15 is lower than 500.00 BTC
2022/01/11 14:00:47 [INFO] Ignoring MIR-BTC because volume 2.32 is lower than 500.00 BTC
2022/01/11 14:00:48 [INFO] Ignoring REP-BTC because volume 3.90 is lower than 500.00 BTC
2022/01/11 14:00:48 [INFO] Ignoring BTRST-BTC because volume 2.22 is lower than 500.00 BTC
2022/01/11 14:00:49 [INFO] Ignoring LTC-BTC because volume 107.40 is lower than 500.00 BTC
2022/01/11 14:00:49 [INFO] Ignoring UNI-BTC because volume 40.29 is lower than 500.00 BTC
2022/01/11 14:00:50 [INFO] Ignoring MKR-BTC because volume 4.87 is lower than 500.00 BTC
2022/01/11 14:00:51 [INFO] Ignoring LINK-BTC because volume 313.67 is lower than 500.00 BTC
2022/01/11 14:00:51 [INFO] Ignoring BCH-BTC because volume 31.70 is lower than 500.00 BTC
2022/01/11 14:00:52 [INFO] Ignoring ENJ-BTC because volume 10.79 is lower than 500.00 BTC
2022/01/11 14:00:53 [INFO] Ignoring WLUNA-BTC because volume 15.60 is lower than 500.00 BTC
2022/01/11 14:00:53 [INFO] Ignoring AVAX-BTC because volume 37.35 is lower than 500.00 BTC
2022/01/11 14:00:54 [INFO] Ignoring MANA-BTC because volume 62.01 is lower than 500.00 BTC
2022/01/11 14:00:54 [INFO] Ignoring FORTH-BTC because volume 2.00 is lower than 500.00 BTC
2022/01/11 14:00:57 [{"market":"ETH-BTC","price":0.07,"size":0.005}]
2022/01/11 14:00:57 [INFO] Ignoring BNT-BTC because volume 2.02 is lower than 500.00 BTC
2022/01/11 14:00:58 [INFO] Ignoring ORN-BTC because volume 1.09 is lower than 500.00 BTC
2022/01/11 14:00:58 [INFO] Ignoring MATIC-BTC because volume 179.18 is lower than 500.00 BTC
2022/01/11 14:00:59 [INFO] Ignoring SKL-BTC because volume 5.12 is lower than 500.00 BTC
2022/01/11 14:01:00 [INFO] Ignoring DOT-BTC because volume 54.96 is lower than 500.00 BTC
2022/01/11 14:01:02 [INFO] Ignoring OGN-BTC because volume 3.60 is lower than 500.00 BTC
2022/01/11 14:01:04 [INFO] Ignoring LRC-BTC because volume 51.40 is lower than 500.00 BTC
2022/01/11 14:01:07 [{"market":"IOTX-BTC","price":0.0000035,"size":100}]
2022/01/11 14:01:08 [INFO] Ignoring DOGE-BTC because volume 14.73 is lower than 500.00 BTC
```
