### ISSUE TITLE
bot stops buying after [ERROR] Cannot find any supports

### ISSUE THREAD

**Issue by stfrbrntyu** [svanas/nefertiti#8]
When you have multiple pairs (--market=PAIR1,PAIR2,PAIR3,PAIR4)

And below error comes up when processing PAIR1
[ERROR] Cannot find any supports. Please ask for fewer supports, or change your other settings.

It will stop processing PAIR2, PAIR3, PAIR4  etc untill the next cycle, that is, if it find supports for PAIR1, else it will stop again.

This only occurs when using the --strict method

Adding --ignore-error doesnt solve it

**Comment by stfrbrntyu** [comment]
that's standard in my command line

**Comment by svanas** [comment]
Fixed in 0.0.150
