### ISSUE TITLE
Any working example command line for signals ?

### ISSUE THREAD

**Issue by abda11ah** [svanas/nefertiti#89]
Hi,
I launched the nefertiti command on linux but I don't understand how to launch a listening on signals from a provider like MiningHamster.

**Available commands are:
    about        About nefertiti.
    agg          Calculates the aggregation level for a given market pair.
    base         Get the base symbol for a given market pair.
    book         Get a list of all public orders on a market.
    buy          Opens new limit buy orders on the specified exchange/market(s).
    cancel       Cancels all your buy or sell orders on a given market.
    coalesce     Coalesce orders having the same price.
    exchanges    Get a list of supported exchanges.
    exit         Exit the specified exchange/market.
    listen       Starts a server listening to the specified port.
    markets      Get a list of available currency pairs for trading.
    notify       Send a notification.
    order        Place an order with the specified exchange.
    quote        Get the quote symbol for a given market pair.
    sell         Automatically opens new sell orders on the specified exchange/market.
    stoploss     Place a stop-loss order with the specified exchange.
    update       Check for a new version.**

Please give me an example command line to make Nefertiti listening on MiningHamster signals while working on a Kucoin account for 1000USDT

**Comment by d00vy** [comment]
Have you seen [the medium articles](hJi4c1YqYtLZz#a40O)?

**Comment by abda11ah** [comment]
Yes, I just saw them, thank you.

(The URL you suggested is a dead link)

**Comment by d00vy** [comment]
> (The URL you suggested is a dead link)
Sorry. Fixed it.

**Comment by abda11ah** [comment]
Hi,
I launched nefertiti to work with cryptobasescanner.
My base currency is BUSD.
The buy command was :
./nefertiti buy --exchange=Binance --signals=cryptobasescanner.com --crypto-base-scanner-key=xxxxxx..... --price=50 --quote=BUSD --min=0.00000050 --volume=1 --repeat=0.0084

After 24 hours I got :
`2022/08/12 07:04:27 [{"market":"TKOBUSD","price":0.317,"size":154.3}]
2022/08/12 07:04:57 [{"market":"TKOBUSD","price":0.317,"size":154.3}]
2022/08/12 07:05:27 [{"market":"TKOBUSD","price":0.317,"size":154.3}]
2022/08/12 07:06:00 [{"market":"TKOBUSD","price":0.317,"size":154.3}]
2022/08/12 07:06:28 [{"market":"TKOBUSD","price":0.317,"size":154.3}]
2022/08/12 07:06:59 [{"market":"TKOBUSD","price":0.317,"size":154.3}]
2022/08/12 07:07:29 [{"market":"TKOBUSD","price":0.317,"size":154.3}]
2022/08/12 07:07:57 [{"market":"TKOBUSD","price":0.317,"size":154.3}]
2022/08/12 07:08:28 [{"market":"TKOBUSD","price":0.317,"size":154.3}]
2022/08/12 07:09:00 [{"market":"TKOBUSD","price":0.317,"size":154.3}]
2022/08/12 07:09:28 [{"market":"TKOBUSD","price":0.317,"size":154.3}]
2022/08/12 07:10:00 [{"market":"TKOBUSD","price":0.317,"size":154.3}]
2022/08/12 07:10:30 [{"market":"TKOBUSD","price":0.317,"size":154.3}]
2022/08/12 07:11:00 [{"market":"TKOBUSD","price":0.317,"size":154.3}]
2022/08/12 07:11:31 [{"market":"TKOBUSD","price":0.317,"size":154.3}]
2022/08/12 07:12:05 [{"market":"TKOBUSD","price":0.317,"size":154.3}]
2022/08/12 07:12:32 [{"market":"TKOBUSD","price":0.317,"size":154.3}]
2022/08/12 07:13:00 [{"market":"TKOBUSD","price":0.317,"size":154.3}]
2022/08/12 07:13:31 [{"market":"TKOBUSD","price":0.317,"size":154.3}]
2022/08/12 07:14:02 [{"market":"TKOBUSD","price":0.317,"size":154.3}]
2022/08/12 07:14:32 [{"market":"TKOBUSD","price":0.317,"size":154.3}]
2022/08/12 07:15:04 [{"market":"TKOBUSD","price":0.317,"size":154.3}]
2022/08/12 07:15:32 [{"market":"TKOBUSD","price":0.317,"size":154.3}]
2022/08/12 07:16:03 [{"market":"TKOBUSD","price":0.317,"size":153.4}]
2022/08/12 07:16:33 [{"market":"TKOBUSD","price":0.317,"size":153.4}]
2022/08/12 07:17:05 [{"market":"TKOBUSD","price":0.317,"size":153.4}]
2022/08/12 07:17:33 [{"market":"TKOBUSD","price":0.317,"size":153.4}]
2022/08/12 07:18:06 [{"market":"TKOBUSD","price":0.317,"size":153.4}]
2022/08/12 07:18:34 [{"market":"TKOBUSD","price":0.317,"size":153.4}]
2022/08/12 07:19:05 [{"market":"TKOBUSD","price":0.317,"size":153.4}]
2022/08/12 07:19:35 [{"market":"TKOBUSD","price":0.317,"size":153.4}]
2022/08/12 07:20:03 [{"market":"TKOBUSD","price":0.317,"size":153.4}]
2022/08/12 07:20:35 [{"market":"TKOBUSD","price":0.317,"size":153.4}]
2022/08/12 07:21:04 [{"market":"TKOBUSD","price":0.317,"size":153.4}]
2022/08/12 07:21:36 [{"market":"TKOBUSD","price":0.317,"size":153.4}]
2022/08/12 07:22:05 [{"market":"TKOBUSD","price":0.317,"size":153.4}]
2022/08/12 07:22:36 [{"market":"TKOBUSD","price":0.317,"size":153.4}]
2022/08/12 07:23:04 [{"market":"TKOBUSD","price":0.317,"size":153.4}]
2022/08/12 07:23:38 [{"market":"TKOBUSD","price":0.317,"size":153.4}]
2022/08/12 07:24:07 [{"market":"TKOBUSD","price":0.317,"size":152.9}]
2022/08/12 07:24:37 [{"market":"TKOBUSD","price":0.317,"size":152.9}]
2022/08/12 07:25:09 [{"market":"TKOBUSD","price":0.317,"size":152.9}]
`

but it won't buy anything.

**Comment by svanas** [comment]
What makes you believe NEF didn't buy? You might want to include `--debug` with your command line.

**Comment by svanas** [comment]
While I believe NEF should be buying, here's an important note about the sell bot. On Binance, the sell bot won't sell any non-BTC paired assets unless you include `--quote=XXX` with your command line, for example: `--quote=BUSC,BTC`

**Comment by abda11ah** [comment]
You mean I must add --quote=XXX at the sell command ?

I can see it doesn't buy anything because I can see it on the binance app.
But I solved the problem, it was because my binance API key did not allow trading operations.

**Comment by svanas** [comment]
> You mean I must add --quote=XXX at the sell command ?

You must add `--quote=BUSD` to your sell command line if you want the sell bot to sell BUSD-paired assets.
