### ISSUE TITLE
Feature : Blacklist a coin from buy signals ?

### ISSUE THREAD

**Issue by abda11ah** [svanas/nefertiti#90]
Hi,
As I see it is not possible to blacklist a coin from buy signals.

So I suggest this as a feature request.

I would like to stop cryptobasescanner from buying TORN coin because Tornado.cash website does not exist anymore, their coin will disappear soon

**Comment by svanas** [comment]
> Hi, As I see it is not possible to blacklist a coin from buy signals.

Why would you want to blacklist a coin? In my experience, the shittiest coins can give you the highest returns.

**Comment by svanas** [comment]
> I would like to stop cryptobasescanner from buying TORN coin because Tornado.cash website does not exist anymore, their coin will disappear soon

$TORN is an ERC-20 on the Ethereum blockchain and as such cannot disappear.

**Comment by abda11ah** [comment]
In my opinion it can quickly disappear because their website is down. So its popularity will decrease until people forgot about it.
