### ISSUE TITLE
allow blocking of ticker lists - exchange delistings case

### ISSUE THREAD

**Issue by katmai** [svanas/nefertiti#91]
It would be great if we could be able to have a way to block buying of assets that were issued delisting notices from exchanges.

i know there's some degree of speculation that could be had but ultimately, these are assets that have been deemed low quality by the exchanges and therefore ceased in trading. it wouldn't do us any good to trade rotten apples.

Let's take the example of Bitcoin Gold which was delisted from Binance last week. i understand speculation has a certain value, but i believe that speculation on dead assets is an unnecessary risk. 

If the garden needs to be pruned, we should probably not try to hold on to the weeds but instead focus on the flowers and the healthy plants that are supposed to bring fruit.

![image](https://user-images.githubusercontent.com/1245160/198012927-431113b9-686b-4582-8f32-08d0d7aa9bfc.png)

As for how - i am totally okay with having to supply a list of tokens like --block=BTG,TCT,NBS,DNT and restart the buy bot.

**Comment by svanas** [comment]
It would be nice if we could connect to Benoist's https://coindelist.com/ for this feature request.

> As for how - i am totally okay with having to supply a list of tokens like --block=BTG,TCT,NBS,DNT and restart the buy bot.

If this is all you need, then I believe you can do this already. NEF includes an arg named `ignore`, for example: `ignore=BTG-BTC,BTG-USDT`

**Comment by katmai** [comment]
having it automated would be great, but if there's already the ignore feature, that is sufficient for me. thanks for the tip!
